language: android
jdk: oraclejdk8
#install:
#  - echo y | android update sdk -u -a -t tools
#  - echo y | android update sdk -u -a -t platform-tools
#  - echo y | android update sdk -u -a -t build-tools-25.0.1
#  - echo y | android update sdk -u -a -t android-25
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
after_success:
  - ./gradlew jacocoTestReport coveralls